apiVersion: v1
kind: Service
metadata:
  name: apiconversao-service
spec:
  selector:
    app: apiconversao
  ports: 
  - port: 80
    #targetPort: 5000
    nodePort: 30000
  type: NodePort #LoadBalancer